mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false

#rocketmq配置
rocketmq:
  name-server: http://MQ_INST_1304221775502770_BXPNI4Il.mq-internet-access.mq-internet.aliyuncs.com:80
  # 生产者配置
  producer:
    isOnOff: on
    # 发送同一类消息的设置为同一个group，保证唯一
    group: rocketmq-group
    groupName: rocketmq-group
    # 服务地址
    namesrvAddr: http://MQ_INST_1304221775502770_BXPNI4Il.mq-internet-access.mq-internet.aliyuncs.com:80
    # 消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    # 发送消息超时时间,默认3000
    sendMsgTimeout: 3000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2

spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/fix_asset_java?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      # 配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
#    host: common.redis.jc-dev.cn # 地址
#    port: 6379  # 端口，默认为6379
#    password: cSpz8iwiIAg0aqGe  # 密码
#    database: 4
#    timeout: 10s # 连接超时时间
    host: 127.0.0.1 # 地址
    port: 6379  # 端口，默认为6379
    password:   # 密码
    database: 4
    timeout: 10s # 连接超时时间
    lettuce:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-active: 8 # 连接池的最大数据库连接数
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
  rabbitmq:
    host: common.rabbitmq.jc-dev.cn
    port: 5672
    username: asset
    password: YyVsmHmsxmEDVtkQ6Zg
    virtual-host: asset
    #rabbitmq消费端配置
    listener:
      simple:
        retry:
          #开启消费者重试
          enabled: true
          #最大重试次数（重试5次还不行则会把消息删掉，默认是不限次数的，次数建议控制在10次以内）
          max-attempts: 5
          #重试间隔时间
          initial-interval: 3000
        acknowledge-mode: manual

#多数据源的配置
#dynamic:
#  datasource:
#    TY:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/fixed_asset?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#      username: root
#      password: root

#腾讯短信
sms:
  appId: 1400097557
  appKey: 73e778823e36a33332e6ad3634d70e4d
  enable: true
  sign: 精臣固定资产

#钉钉请求地址
ding:
  host-url: https://oapi.dingtalk.com
  robot-token: 4cffa7017f54a461c344b3f215c0bf7ccbcabdd32d73de2873b1ffbe23b50208
  robot-secret: SEC4f283a7b42e7fdeaa9b6b2fdabc0b1c2de4601ae028cbd3b4ec8c1082315908d

#邮箱
email:
  host: smtp.163.com
  from: dingke0914@163.com
  password: XQUTZEDLJBGVQKNR


