feign:
  remote: http://127.0.0.1:8182

spring:
  # redis 配置
  redis:
#    host: common.redis.jc-dev.cn # 地址
#    port: 6379  # 端口，默认为6379
#    password: cSpz8iwiIAg0aqGe  # 密码
#    database: 4
#    timeout: 10s # 连接超时时间
    host: 127.0.0.1 # 地址
    port: 6379  # 端口，默认为6379
    password:   # 密码
    database: 4
    timeout: 10s # 连接超时时间
  #rabbitmq基本配置
  rabbitmq:
    host: common.rabbitmq.jc-dev.cn
    port: 5672
    username: asset
    password: YyVsmHmsxmEDVtkQ6Zg
    virtual-host: asset
    #rabbitmq消费端配置
    listener:
      simple:
        retry:
          #开启消费者重试
          enabled: true
          #最大重试次数（重试5次还不行则会把消息删掉，默认是不限次数的，次数建议控制在10次以内）
          max-attempts: 5
          #重试间隔时间
          initial-interval: 3000
        acknowledge-mode: manual

# Swagger配置
swagger:
  enabled: true

#rocketmq配置
rocketmq:
  name-server: http://MQ_INST_1304221775502770_BXPNI4Il.mq-internet-access.mq-internet.aliyuncs.com:80
  # 生产者配置
  producer:
    isOnOff: on
    # 发送同一类消息的设置为同一个group，保证唯一
    group: rocketmq-group
    groupName: rocketmq-group
    # 服务地址
    namesrvAddr: http://MQ_INST_1304221775502770_BXPNI4Il.mq-internet-access.mq-internet.aliyuncs.com:80
    # 消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    # 发送消息超时时间,默认3000
    sendMsgTimeout: 3000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2